version: '3.7'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "587:587"
      - "993:993"
      - "995:995"
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DOMAIN1=${DOMAIN1}
      - DOMAIN2=${DOMAIN2}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
      - ADMIN_DOMAIN=${ADMIN_DOMAIN}
      - WEBMAIL_DOMAIN=${WEBMAIL_DOMAIN}
    volumes:
      - web_data:/var/www/html
      - db_data:/var/lib/mysql
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  web_data:
  db_data:
