version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./apache-config:/etc/apache2/sites-available
      - ./postfix-config:/etc/postfix
      - ./dovecot-config:/etc/dovecot
    networks:
      - webnet

networks:
  webnet:
