version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "587:587"
      - "993:993"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
      - ./www:/var/www/html
      - ./mail:/var/mail
      - ./letsencrypt:/etc/letsencrypt
      - ./apache-config:/etc/apache2/sites-available
    networks:
      - webnet

networks:
  webnet:
