version: '3.8'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
      - "25:25"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      DOMAIN1: ${DOMAIN1}
      DOMAIN2: ${DOMAIN2}
      MAIL_DOMAIN: ${MAIL_DOMAIN}
      ADMIN_DOMAIN: ${ADMIN_DOMAIN}
      WEBMAIL_DOMAIN: ${WEBMAIL_DOMAIN}
    volumes:
      - web_data:/var/www/html

volumes:
  db_data:
  web_data:
